theme: jekyll-theme-cayman
title: Simple Linear Regression
author: Nitin Malik
navbar-links:
  About Me: "Professor of Data Science"
  Resources:
    - Neural Netorks: "http://neuralnetworksanddeeplearning.com/"
    - markdown: "https://www.markdowntutorial.com/"
    - Python: "https://www.hackerrank.com/domains/python"
  Author's home: "https://www.linkedin.com/in/drnitinmalik/"
social-network-links:
  email: "nitinmalik77@gmail.com"
  facebook: dr.malik.nitin
  github: drnitinmalik
  twitter: drnitinmalik1
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
Feel free to bookmark this webpag to keep an eye on the updates
