theme: jekyll-theme-cayman
title: Simple Linear Regression
tagline: Pre-regression steps, Regression model, Post-regression analysis
description: Pre-regression steps, Regression model, Post-regression analysis
baseurl: "/simple-linear-regression"
author: Nitin Malik
show_downloads: true
# About/contact
author:
  name:       Nitin Malik
  url:        https://www.linkedin.com/in/drnitinmalik
navbar-links:
  About Me: "Professor of Data Science"
  Resources:
    - Neural Netorks: "http://neuralnetworksanddeeplearning.com/"
    - markdown: "https://www.markdowntutorial.com/"
    - Python: "https://www.hackerrank.com/domains/python"
  Author's home: "https://www.linkedin.com/in/drnitinmalik/"
social-network-links:
  email: "nitinmalik77@gmail.com"
  facebook: dr.malik.nitin
  github: drnitinmalik
  twitter: drnitinmalik1
  linkedin: drnitinmalik
  ORCID: 0000-0003-1484-9841
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  google-scholar: your google scholar
# rss-description: RSS Link

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true
  
# How to display the link to your website in the footer
url-pretty: "https://www.linkedin.com/in/drnitinmalik/"
Feel free to bookmark this webpag to keep an eye on the updates
