theme: jekyll-theme-cayman
title: Simple Linear Regression
tagline: Regression line, Overfitting, Underfitting, Bias, Variance
description: Pre-regression steps, Regression model, Post-regression analysis
baseurl: /simple-linear-regression/
url: https://drnitinmalik.github.io
show_downloads: true
future: true
markdown: kramdown
# About/contact
author:
  name: Nitin Malik
  bio: Professor of Data Science
  location: India
  url: https://www.linkedin.com/in/drnitinmalik
navbar-links:
  About Me: Professor of Data Science
  Resources:
    - Neural Netorks: http://neuralnetworksanddeeplearning.com/
    - markdown: https://www.markdowntutorial.com/
    - Python: https://www.hackerrank.com/domains/python
  Author's home: https://www.linkedin.com/in/drnitinmalik/
social-network-links:
  email: nitinmalik77@gmail.com
  facebook: dr.malik.nitin
  github: drnitinmalik
  twitter: drnitinmalik1
  linkedin: drnitinmalik
  ORCID: 0000-0003-1484-9841
#  reddit: yourname
  linkedin: drnitinmalik
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  instagram: deanat78
#  youtube: user/drnitinmalik
#  telephone: +918010529215
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  google-scholar: your google scholar
# rss-description: RSS Link

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true
  
# How to display the link to your website in the footer
url-pretty: https://www.linkedin.com/in/drnitinmalik/
footer:
  links:
    url: https://www.linkedin.com/in/drnitinmalik/
#Feel free to bookmark this webpag to keep an eye on the updates
